### Creating User 
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "tests@test.com",
    "password": "samplepassword"
}

### Logging in User
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "tests@test.com",
    "password": "samplepassword"
}

### Signing Out User
POST http://localhost:3000/auth/signout

### Get All User Email
GET http://localhost:3000/auth/?email=jamespaulengay@gmail.com

### Get User by Id
GET http://localhost:3000/auth/5

### Delete User 
DELETE http://localhost:3000/auth/12312312

### Update User
PATCH http://localhost:3000/auth/112123
Content-Type: application/json

 { 
     "email": "emailbuddy@example.com"
 }

### Who Am I
GET http://localhost:3000/auth/whoAmI

